version: "3.8"

services:
  db:
    image: postgres:15
    container_name: granula-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: granula
      POSTGRES_USER: granula_user
      POSTGRES_PASSWORD: granula_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U granula_user -d granula"]
      interval: 5s
      timeout: 3s
      retries: 10

  adminer:
    image: adminer:4
    container_name: granula-adminer
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8080:8080"

volumes:
  pgdata:
    name: granula-pgdata 